[package]
name = "rust_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
axum = { version = "0.8.4", default-features = false, features = [
    "tokio",
    "http1",
] }
