[package]
name = "speed_up"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
hyper = { version = "1.6.0", features = ["client", "http2"] }
reqwest = "0.12.20"
tokio = { version = "1.45.1", features = ["full"] }
